### PR TITLE
Interpolation point error

### PR DESCRIPTION
**Pull request by oriolcg**
Fixing issue #727, closing #727 .

### CODE REVIEW

**Comment by fverdugo** [comment]
@Balaje are you happy with this?

**Comment by oriolcg** [comment]
@fverdugo, I did an update trying to go in the direction that @Balaje suggested.  I now use the `searchmethod` in `Interpolable` to define an optional argument with the number of nearest vertices (default = 1). This is much cleaner, this optional argument can be changed directly from the user driver (if needed) as follows:

```julia
sm=KDTreeSearch(num_nearest_vertices=10)
uₕ = interpolate_everywhere(Interpolable(uh_0;searchmethod=sm),U)
```

**Comment by Balaje** [comment]
@oriolcg @fverdugo Yes, this is what I had in mind. It gives the user an option to provide a way to set the search level in case the algorithm misses points like this.

**Review by fverdugo — CHANGES_REQUESTED** [review]
@oriolcg Can you fabricate a simple example and add it that reproduces the bug that this PR wants to fix?

**Comment by oriolcg** [comment]
@fverdugo, I added the test in https://github.com/gridap/Gridap.jl/pull/729/commits/6838ed5c5becc8e4d0785cb04819066cc108b637. The PR is ready

**Review by fverdugo — APPROVED** [review]

**Pull request merged**
