### PR TITLE
switch argument order of interpolate to function first

### PR DESCRIPTION
**Pull request by jw3126**
This PR is should be against release 0.14 right? If that's correct, I will go ahead and fix the depwarns.

### CODE REVIEW

**Comment by fverdugo** [comment]
Hi @jw3126 !

We can merge it against 0.14.

Since it is a new version, please replace the deprecation warnings by errors (with a meaning full error message) to make sure that the old notation is not used anymore from 0.14 on. 

Please add also a short note in NEWS.md in section `## Changed`

Thanks a lot!

**Comment by jw3126** [comment]
> Since it is a new version, please replace the deprecation warnings by errors (with a meaning full error message) to make sure that the old notation is not used anymore from 0.14 on.

I think it would be better to do 0.14 depwarn and fully remove in 0.15. Note that you can do `julia --depwarn=error` to hunt down old notation.

**Comment by fverdugo** [comment]
As you feel more confortable. I have no strong feelings on this. I just wanted to fix it out now.

In any case, what is important that all the test in the PR pass without dep. warnings.

**Comment by jw3126** [comment]
Yeah, I use `julia --depwarn=error` locally to do this (we could add this to CI, but I think having it always active is more annoying than useful).

**Pull request merged**
