### PR TITLE
Customisable measure data domain style

### PR DESCRIPTION
**Pull request by ericneiva**
Solves #877.

After discussion with @santiagobadia, I have changed the `CellQuadrature` constructors such that now both data and integration domain styles are keyword arguments that the user can customise.

Note that this PR introduces a minor change in the API.

### CODE REVIEW

**Comment by amartinhuertas** [comment]
Hi @ericneiva ! Thanks for the PR. I agree the API is much cleaner now.

My only concern is that if we accept the PR as it is, then we should also do major release, correct?

Can we may be add the old signatures and add corresponding deprecated warnings so that we avoid a major release? 

Also note that, since this PR (my fault sorry), we also added another kind of measure, called `CompositeMeasure`, which is leveraged whenever you have integration on adapted meshes. Not sure if this has to be taken into account when updating this branch from `master` ...

**Comment by amartinhuertas** [comment]
> Also note that, since this PR (my fault sorry), we also added another kind of measure, called CompositeMeasure, which is leveraged whenever you have integration on adapted meshes. Not sure if this has to be taken into account when updating this branch from master ...

Forget this. I now see you are already taking into account `CompositeMeasure` in your PR ...

**Comment by amartinhuertas** [comment]
Also dont forget to add the corresponding entry in NEWS.md ... Thanks!

**Comment by ericneiva** [comment]
Hi, @amartinhuertas,

> I agree the API is much cleaner now.

Good to know :)

> Can we may be add the old signatures and add corresponding deprecated warnings so that we avoid a major release?

Done. Let me know if the deprecated warnings are ok.

> Also dont forget to add the corresponding entry in NEWS.md

Done.

Thank you very much for your review!

**Comment by amartinhuertas** [comment]
FYI, just in case you did not know, I found this article on deprecation quite useful: 

https://invenia.github.io/blog/2022/06/17/deprecating-in-julia/

All good now. Accepting PR!

**Comment by ericneiva** [comment]
Great, thanks!

> FYI, just in case you did not know, I found this article on deprecation quite useful:

Useful, indeed, thanks for sharing, @amartinhuertas

**Pull request merged**
