### PR TITLE
Change the type of sizes/partition member variables of CartesianDescriptor 

### PR DESCRIPTION
**Pull request by amartinhuertas**
See issue #244

### CODE REVIEW

**Comment by amartinhuertas** [comment]
Hi @fverdugo! You can proceed with your code review. One doubt that comes into my mind. The set of changes in this PR to which ChangeLog cathegory should go? My guess is that they should go to `Changed`, as we have modified the behaviour of a generic function which is in the public API of Gridap.jl, in particular, `CartesianDescriptor`. Agreed?

**Comment by fverdugo** [comment]
> The set of changes in this PR to which ChangeLog cathegory should go? My guess is that they should go to Changed, as we have modified the behaviour of a generic function which is in the public API of Gridap.jl, in particular, CartesianDescriptor. Agreed?

Yes, moreover we are changing the types of the fields in the struct, which in this case are public fields.

**Comment by fverdugo** [comment]
@amartinhuertas I have added type annotations to the arguments in the inner constructor of `CartesianDescriptor`. I have realized that these arguments cannot be of arbitrary type since some particular combinations can conflict with the method `CartesianDescriptor(pmin::Point,pmax::Point,partition)`

**Comment by fverdugo** [comment]
@amartinhuertas Can you write a new entry in NEWS.md about this PR once it is merged?

**Comment by amartinhuertas** [comment]
> @amartinhuertas Can you write a new entry in NEWS.md about this PR once it is merged?

Done in f560fa245e68284b06dfb8ebdb2d2899d26253fc

**Pull request merged**
