### PR TITLE
Trying to fix master by restricting WriteVTK version

### PR DESCRIPTION
**Pull request by fverdugo**

### CODE REVIEW

**Comment by PetrKryslUCSD** [comment]
So are you saying that VTK 1.7 is (was) broken?

**Comment by amartinhuertas** [comment]
Hi @PetrKryslUCSD! 

the package update `↑ WriteVTK v1.6.0 ⇒ v1.7.1` breaks some ot the tests in our project. 

See the following issue for further details: https://github.com/gridap/Gridap.jl/issues/286

We did not dig deep yet into the cause of the broken test, but accordingly to the error backtrace reported in  https://github.com/gridap/Gridap.jl/issues/286, we suspect that the changes in v.1.7.0 introduced in `MeshCell` may well behind the broken test (see the following comment: https://github.com/gridap/Gridap.jl/issues/286#issuecomment-647328987 for more details). 

Are u experiencing issues with VTK 1.7 as well?

**Comment by amartinhuertas** [comment]
I think I could fix the broken tests in our particular case (comprehensive test suite still underway).

See https://github.com/gridap/Gridap.jl/pull/324/commits/ccd756543ad6c1c420757681519ca60710b1b1fb for more details.

**Comment by PetrKryslUCSD** [comment]
No, I am on
  [64499a7a] WriteVTK v1.7.1  
and I have seen no errors.

**Comment by jipolanco** [comment]
Hi, I just noticed this issue. I apologise for the breaking changes in WriteVTK, and I'm glad to see that you figured out the solution in #324.

To clarify, the `MeshCell` type in WriteVTK was modified in v1.7 to support the definition of polygonal meshes, which are a specific type of unstructured mesh. As I mentioned in a [related issue](https://github.com/CliMA/ClimateMachine.jl/issues/1282#issuecomment-650314037), I didn't expect this change to break other projects such as this one.

**Pull request merged**
